// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9edB-cEsuCSYRDgCICvAWR2X-gfwnSm8',
    appId: '1:261563193700:web:bc77d37e46a0a3e7eec271',
    messagingSenderId: '261563193700',
    projectId: 'nhac-backend',
    authDomain: 'nhac-backend.firebaseapp.com',
    storageBucket: 'nhac-backend.firebasestorage.app',
    measurementId: 'G-NMK7N0DG3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI3jMGshUZGdmJKdyc-mSxFrHyRkspS-U',
    appId: '1:261563193700:android:c125c7b1b1497102eec271',
    messagingSenderId: '261563193700',
    projectId: 'nhac-backend',
    storageBucket: 'nhac-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdTHzWvbYbl5YE2Hb2Mes82RuNlz-yPv8',
    appId: '1:261563193700:ios:63b545ffac7c9777eec271',
    messagingSenderId: '261563193700',
    projectId: 'nhac-backend',
    storageBucket: 'nhac-backend.firebasestorage.app',
    androidClientId: '261563193700-j6opr2sih19ejvutug0nlg3ho991gulq.apps.googleusercontent.com',
    iosClientId: '261563193700-45fcvn0u38f7pt0lkl3ne68idbdqte96.apps.googleusercontent.com',
    iosBundleId: 'com.feentzs.nhac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdTHzWvbYbl5YE2Hb2Mes82RuNlz-yPv8',
    appId: '1:261563193700:ios:63b545ffac7c9777eec271',
    messagingSenderId: '261563193700',
    projectId: 'nhac-backend',
    storageBucket: 'nhac-backend.firebasestorage.app',
    androidClientId: '261563193700-j6opr2sih19ejvutug0nlg3ho991gulq.apps.googleusercontent.com',
    iosClientId: '261563193700-45fcvn0u38f7pt0lkl3ne68idbdqte96.apps.googleusercontent.com',
    iosBundleId: 'com.feentzs.nhac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9edB-cEsuCSYRDgCICvAWR2X-gfwnSm8',
    appId: '1:261563193700:web:316ee8b7d7e4b62eeec271',
    messagingSenderId: '261563193700',
    projectId: 'nhac-backend',
    authDomain: 'nhac-backend.firebaseapp.com',
    storageBucket: 'nhac-backend.firebasestorage.app',
    measurementId: 'G-KPZGVMBT5E',
  );
}
