name: Flutter Build APK (Debug)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          mkdir -p android/app
          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Verify google-services.json
        run: |
          if [ -f "android/app/google-services.json" ]; then
            echo "google-services.json criado com sucesso."
            # Verifica se o arquivo não está vazio
            if [ -s "android/app/google-services.json" ]; then
              echo "O arquivo tem conteúdo."
            else
              echo "ERRO: O arquivo está vazio. Verifique seu secret GOOGLE_SERVICES_JSON."
              exit 1
            fi
          else
            echo "ERRO: google-services.json NÃO foi encontrado."
            exit 1
          fi

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 1